# Generated by Django 5.2 on 2025-04-09 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'Звено', 'verbose_name_plural': 'Звенья'},
        ),
        migrations.AlterField(
            model_name='node',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='api.node'),
        ),
    ]
