# Generated by Django 5.2 on 2025-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_node_options_alter_node_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
