# Generated by Django 5.1.8 on 2025-04-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_node_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.node'),
        ),
    ]
