version: '3.1'
services:
  django_test_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432"

    restart: always
    networks:
       - custom

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - django_test_db
      - redis
    networks:
      - custom

  celery:
    build: .
    command: sh -c "cd src/test_app && celery -A test_app worker --loglevel=info"
    depends_on:
      - web
      - redis
    networks:
      - custom

  celery_beat:
    build: .
    command: sh -c "cd src/test_app && celery -A test_app beat --loglevel=info"
    depends_on:
      - web
      - redis
    networks:
      - custom

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - custom


networks:
  custom:
    driver: bridge
